apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurations-mysql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configurations-mysql
  template:
    metadata:
      labels:
        app: configurations-mysql
    spec:
      containers:
        - name: configurations-mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: PASSWORD
            - name: MYSQL_USER
              value: 'rooty'
            - name: MYSQL_DATABASE
              value: 'ib_configurations'
            - name: MYSQL_PASSWORD
              value: '1234'
---
apiVersion: v1
kind: Service
metadata:
  name: configurations-mysql-srv
spec:
  selector:
    app: configurations-mysql
  ports:
     - name: configurations-db
       protocol: TCP
       port: 3306
       targetPort: 3306
  
