apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurations-depl
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: configurations
  template:
    metadata:
      labels:
        app: configurations
    spec:
      containers:
        - name: configurations
          image: animesh1008/configurations
          env:
          - name: MYSQL_HOST
            value: 'localhost'
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: PASSWORD
          - name: MYSQL_USER
            value: 'rooty'
          - name: MYSQL_DATABASE
            value: 'ib_configurations'
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
          - name: MYSQL_PASSWORD
            value: '1234'
---
apiVersion: v1
kind: Service
metadata:
  name: configurations-srv
spec:
  selector:
    app: configurations
  ports:
    - name: configurations
      protocol: TCP
      port: 3000
      targetPort: 3000